// seed.js — Run once: node seed.js
const mongoose = require("mongoose");
require("dotenv").config();

mongoose.connect(process.env.MONGODB_URI || "mongodb://localhost:27017/theatron")
  .then(() => console.log("✅ Connected to MongoDB"))
  .catch(err => { console.error("❌ Connection error:", err); process.exit(1); });

const movieSchema = new mongoose.Schema({
  title: String, year: Number, genre: [String],
  rating: Number, score: Number, director: String,
  cast: [String], description: String, poster: String,
  duration: Number, language: String, featured: Boolean,
}, { timestamps: true });

const Movie = mongoose.model("Movie", movieSchema);
const T = "https://image.tmdb.org/t/p/w500";

const movies = [
  // SCI-FI
  { title:"Dune: Part Two", year:2024, genre:["Sci-Fi","Adventure"], rating:8.5, score:93, director:"Denis Villeneuve", cast:["Timothée Chalamet","Zendaya","Rebecca Ferguson"], description:"Paul Atreides unites with the Fremen to wage war against House Harkonnen.", poster:`${T}/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg`, duration:166, language:"English", featured:true },
  { title:"Inception", year:2010, genre:["Sci-Fi","Thriller","Action"], rating:8.8, score:87, director:"Christopher Nolan", cast:["Leonardo DiCaprio","Joseph Gordon-Levitt","Elliot Page"], description:"A thief who steals corporate secrets through dream-sharing is given the task of planting an idea.", poster:`${T}/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg`, duration:148, language:"English", featured:true },
  { title:"Interstellar", year:2014, genre:["Sci-Fi","Drama","Adventure"], rating:8.7, score:73, director:"Christopher Nolan", cast:["Matthew McConaughey","Anne Hathaway","Jessica Chastain"], description:"A team of explorers travel through a wormhole in space to ensure humanity's survival.", poster:`${T}/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg`, duration:169, language:"English", featured:false },
  { title:"The Matrix", year:1999, genre:["Sci-Fi","Action"], rating:8.7, score:83, director:"Lana Wachowski", cast:["Keanu Reeves","Laurence Fishburne","Carrie-Anne Moss"], description:"A computer hacker learns about the true nature of reality and joins a rebellion against the machines.", poster:`${T}/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg`, duration:136, language:"English", featured:false },
  { title:"Blade Runner 2049", year:2017, genre:["Sci-Fi","Drama","Mystery"], rating:8.0, score:88, director:"Denis Villeneuve", cast:["Ryan Gosling","Harrison Ford","Ana de Armas"], description:"A young blade runner's discovery of a long-buried secret leads him to track down former blade runner Rick Deckard.", poster:`${T}/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg`, duration:164, language:"English", featured:false },
  { title:"Arrival", year:2016, genre:["Sci-Fi","Drama","Mystery"], rating:7.9, score:94, director:"Denis Villeneuve", cast:["Amy Adams","Jeremy Renner","Forest Whitaker"], description:"A linguist works with the military to communicate with alien lifeforms after twelve spacecraft appear.", poster:`${T}/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg`, duration:116, language:"English", featured:false },
  { title:"2001: A Space Odyssey", year:1968, genre:["Sci-Fi","Adventure"], rating:8.3, score:92, director:"Stanley Kubrick", cast:["Keir Dullea","Gary Lockwood","William Sylvester"], description:"After discovering a mysterious artifact buried beneath the Lunar surface, mankind sets off to find its origins.", poster:`${T}/ve72VxNqjGM69Uky4WTo2bK6rfq.jpg`, duration:149, language:"English", featured:false },
  { title:"Alien", year:1979, genre:["Sci-Fi","Horror"], rating:8.5, score:98, director:"Ridley Scott", cast:["Sigourney Weaver","Tom Skerritt","John Hurt"], description:"After a commercial vessel is hijacked by an unknown organism, the crew must fight for survival.", poster:`${T}/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg`, duration:117, language:"English", featured:false },
  { title:"Gravity", year:2013, genre:["Sci-Fi","Drama","Thriller"], rating:7.7, score:96, director:"Alfonso Cuaron", cast:["Sandra Bullock","George Clooney"], description:"Two astronauts work together to survive after an accident leaves them adrift in space.", poster:`${T}/44immBwzhDVyjn87b3x3l9mlhAD.jpg`, duration:91, language:"English", featured:false },
  { title:"Ex Machina", year:2014, genre:["Sci-Fi","Drama","Mystery"], rating:7.7, score:92, director:"Alex Garland", cast:["Domhnall Gleeson","Alicia Vikander","Oscar Isaac"], description:"A young programmer is selected to participate in a ground-breaking experiment in synthetic intelligence.", poster:`${T}/btPsujbGHHDm7iHFqbtiVqtLECU.jpg`, duration:108, language:"English", featured:false },
  { title:"The Martian", year:2015, genre:["Sci-Fi","Adventure","Drama"], rating:8.0, score:91, director:"Ridley Scott", cast:["Matt Damon","Jessica Chastain","Kristen Wiig"], description:"An astronaut becomes stranded on Mars and must rely on ingenuity to signal that he is alive.", poster:`${T}/5aGhaIHYuQbqlHWvWYqMCnj40y2.jpg`, duration:144, language:"English", featured:false },
  { title:"Her", year:2013, genre:["Sci-Fi","Drama","Romance"], rating:8.0, score:94, director:"Spike Jonze", cast:["Joaquin Phoenix","Scarlett Johansson","Amy Adams"], description:"A lonely writer develops an unlikely relationship with an operating system designed to meet his every need.", poster:`${T}/eCOtqtfvn7mxGeCGHBhat1wEBIN.jpg`, duration:126, language:"English", featured:false },
  { title:"Annihilation", year:2018, genre:["Sci-Fi","Horror","Adventure"], rating:6.9, score:88, director:"Alex Garland", cast:["Natalie Portman","Jennifer Jason Leigh","Tessa Thompson"], description:"A biologist signs up for a dangerous expedition into a mysterious zone where the laws of nature do not apply.", poster:`${T}/mbsNhVEMEwcCqiKaHmJgbcr9Q6u.jpg`, duration:115, language:"English", featured:false },
  { title:"Moon", year:2009, genre:["Sci-Fi","Drama","Mystery"], rating:7.9, score:89, director:"Duncan Jones", cast:["Sam Rockwell","Kevin Spacey"], description:"Astronaut Sam Bell has a quintessentially personal encounter toward the end of his three-year stint on the Moon.", poster:`${T}/oMnUXKSWqCEsHJDGHXbWDXHvVuB.jpg`, duration:97, language:"English", featured:false },

  // DRAMA
  { title:"Oppenheimer", year:2023, genre:["Drama","History","Thriller"], rating:8.9, score:93, director:"Christopher Nolan", cast:["Cillian Murphy","Emily Blunt","Matt Damon"], description:"The story of J. Robert Oppenheimer and his role in the development of the first nuclear weapon.", poster:`${T}/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg`, duration:180, language:"English", featured:true },
  { title:"The Shawshank Redemption", year:1994, genre:["Drama"], rating:9.3, score:91, director:"Frank Darabont", cast:["Tim Robbins","Morgan Freeman","Bob Gunton"], description:"Two imprisoned men bond over years, finding solace and eventual redemption through acts of common decency.", poster:`${T}/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg`, duration:142, language:"English", featured:false },
  { title:"Forrest Gump", year:1994, genre:["Drama","Romance","Comedy"], rating:8.8, score:71, director:"Robert Zemeckis", cast:["Tom Hanks","Robin Wright","Gary Sinise"], description:"The presidencies of Kennedy and Johnson through the eyes of an Alabama man with an extraordinary life.", poster:`${T}/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg`, duration:142, language:"English", featured:false },
  { title:"Schindler's List", year:1993, genre:["History","Drama","War"], rating:9.0, score:98, director:"Steven Spielberg", cast:["Liam Neeson","Ralph Fiennes","Ben Kingsley"], description:"A German businessman saves the lives of over a thousand Jewish refugees during the Holocaust.", poster:`${T}/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg`, duration:195, language:"English", featured:false },
  { title:"Whiplash", year:2014, genre:["Drama","Music"], rating:8.5, score:94, director:"Damien Chazelle", cast:["Miles Teller","J.K. Simmons","Melissa Benoist"], description:"A promising young drummer enrolls at a cut-throat music conservatory where dreams and desperation collide.", poster:`${T}/7fn624j5lj3xTme2SgiLCeuedmO.jpg`, duration:107, language:"English", featured:false },
  { title:"Good Will Hunting", year:1997, genre:["Drama","Romance"], rating:8.3, score:97, director:"Gus Van Sant", cast:["Matt Damon","Robin Williams","Ben Affleck"], description:"Will Hunting, a janitor at MIT, has a gift for mathematics but needs help finding direction in life.", poster:`${T}/bABCBKYBK7A5G1x0FzoeoNfuj2.jpg`, duration:126, language:"English", featured:false },
  { title:"A Beautiful Mind", year:2001, genre:["Drama","Biography"], rating:8.2, score:75, director:"Ron Howard", cast:["Russell Crowe","Ed Harris","Jennifer Connelly"], description:"After John Nash accepts secret work in cryptography, his life takes a drastic turn.", poster:`${T}/zwzWCmH72OSC9NA0ipoqynmDiDQ.jpg`, duration:135, language:"English", featured:false },
  { title:"The Pursuit of Happyness", year:2006, genre:["Drama","Biography"], rating:8.0, score:67, director:"Gabriele Muccino", cast:["Will Smith","Jaden Smith","Thandie Newton"], description:"A struggling salesman takes custody of his son as he begins a life-changing professional career.", poster:`${T}/lBmYr1PkLfmBGEE0ywDtKFfFJNp.jpg`, duration:117, language:"English", featured:false },
  { title:"12 Years a Slave", year:2013, genre:["Drama","History"], rating:8.1, score:97, director:"Steve McQueen", cast:["Chiwetel Ejiofor","Michael Fassbender","Lupita Nyong'o"], description:"In the antebellum United States, Solomon Northup, a free Black man, is abducted and sold into slavery.", poster:`${T}/xdANQHzFGgFqm73hFWNGdPEj7MB.jpg`, duration:134, language:"English", featured:false },
  { title:"Marriage Story", year:2019, genre:["Drama","Romance"], rating:7.9, score:95, director:"Noah Baumbach", cast:["Scarlett Johansson","Adam Driver","Laura Dern"], description:"A stage director and his actor wife struggle through a grueling bicoastal divorce.", poster:`${T}/pZekG6xabTmZxjmYw10wN84Hp8d.jpg`, duration:136, language:"English", featured:false },
  { title:"Moonlight", year:2016, genre:["Drama"], rating:7.4, score:99, director:"Barry Jenkins", cast:["Trevante Rhodes","Andre Holland","Naomie Harris"], description:"A young African-American man grapples with his identity and sexuality across three defining chapters.", poster:`${T}/qAwFbszPGS6nEEGIyCzPiSVlRGf.jpg`, duration:111, language:"English", featured:false },
  { title:"Tár", year:2022, genre:["Drama","Music"], rating:7.5, score:91, director:"Todd Field", cast:["Cate Blanchett","Noemie Merlant","Nina Hoss"], description:"Set in the international world of classical music, the film centers on conductor Lydia Tar.", poster:`${T}/kqlBDUXFVGGUrHoVHHbOLbdHuJA.jpg`, duration:158, language:"English", featured:false },

  // CRIME / THRILLER
  { title:"The Godfather", year:1972, genre:["Crime","Drama"], rating:9.2, score:97, director:"Francis Ford Coppola", cast:["Marlon Brando","Al Pacino","James Caan"], description:"The aging patriarch of an organized crime dynasty transfers control to his reluctant son.", poster:`${T}/3bhkrj58Vtu7enYsLLeHClarADY.jpg`, duration:175, language:"English", featured:true },
  { title:"Pulp Fiction", year:1994, genre:["Crime","Drama","Thriller"], rating:8.9, score:92, director:"Quentin Tarantino", cast:["John Travolta","Uma Thurman","Samuel L. Jackson"], description:"The lives of two mob hitmen, a boxer, and a pair of bandits intertwine in tales of violence.", poster:`${T}/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg`, duration:154, language:"English", featured:false },
  { title:"The Dark Knight", year:2008, genre:["Action","Crime","Thriller"], rating:9.0, score:94, director:"Christopher Nolan", cast:["Christian Bale","Heath Ledger","Aaron Eckhart"], description:"Batman faces the Joker, a criminal mastermind who plunges Gotham into anarchy.", poster:`${T}/qJ2tW6WMUDux911r6m7haRef0WH.jpg`, duration:152, language:"English", featured:true },
  { title:"No Country for Old Men", year:2007, genre:["Crime","Drama","Thriller"], rating:8.2, score:93, director:"Joel Coen", cast:["Tommy Lee Jones","Javier Bardem","Josh Brolin"], description:"Violence and mayhem ensue after a hunter stumbles upon drug money in the Texas desert.", poster:`${T}/6d5XOczc2AvFANpJGwrBDEMkLDc.jpg`, duration:122, language:"English", featured:false },
  { title:"Goodfellas", year:1990, genre:["Crime","Drama","Biography"], rating:8.7, score:96, director:"Martin Scorsese", cast:["Ray Liotta","Robert De Niro","Joe Pesci"], description:"The story of Henry Hill and his life in the mob, covering his rise and fall.", poster:`${T}/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg`, duration:146, language:"English", featured:false },
  { title:"Joker", year:2019, genre:["Drama","Crime","Thriller"], rating:8.4, score:69, director:"Todd Phillips", cast:["Joaquin Phoenix","Robert De Niro","Zazie Beetz"], description:"A mentally troubled stand-up comedian descends into madness and becomes a criminal mastermind.", poster:`${T}/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg`, duration:122, language:"English", featured:false },
  { title:"The Silence of the Lambs", year:1991, genre:["Thriller","Crime","Horror"], rating:8.6, score:96, director:"Jonathan Demme", cast:["Jodie Foster","Anthony Hopkins","Scott Glenn"], description:"A young FBI cadet seeks the help of an imprisoned cannibal killer to catch another serial killer.", poster:`${T}/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg`, duration:118, language:"English", featured:false },
  { title:"Zodiac", year:2007, genre:["Crime","Drama","Mystery"], rating:7.7, score:89, director:"David Fincher", cast:["Jake Gyllenhaal","Robert Downey Jr.","Mark Ruffalo"], description:"A San Francisco cartoonist becomes an amateur detective obsessed with the Zodiac serial killer.", poster:`${T}/ogl5TbNnW5DRBpGBsrYUxzNYrPF.jpg`, duration:157, language:"English", featured:false },
  { title:"Heat", year:1995, genre:["Crime","Drama","Thriller"], rating:8.3, score:86, director:"Michael Mann", cast:["Al Pacino","Robert De Niro","Val Kilmer"], description:"A group of professional bank robbers start to feel the heat from police when they target a cop's family.", poster:`${T}/zMyfPUelumio3tiDKPffaUpsQTD.jpg`, duration:170, language:"English", featured:false },
  { title:"Gone Girl", year:2014, genre:["Thriller","Drama","Mystery"], rating:8.1, score:87, director:"David Fincher", cast:["Ben Affleck","Rosamund Pike","Neil Patrick Harris"], description:"With his wife's sudden disappearance, a man becomes the prime suspect in her murder.", poster:`${T}/2lyaHKoNwDKaYBLUCHCDkgISbj3.jpg`, duration:149, language:"English", featured:false },
  { title:"Se7en", year:1995, genre:["Crime","Drama","Mystery"], rating:8.6, score:65, director:"David Fincher", cast:["Brad Pitt","Morgan Freeman","Kevin Spacey"], description:"Two detectives hunt a serial killer who uses the seven deadly sins as his motives.", poster:`${T}/6yoghtyTpznpBik8EngEmJskVnS.jpg`, duration:127, language:"English", featured:false },
  { title:"Prisoners", year:2013, genre:["Thriller","Drama","Mystery"], rating:8.1, score:81, director:"Denis Villeneuve", cast:["Hugh Jackman","Jake Gyllenhaal","Viola Davis"], description:"When two girls go missing, a desperate father takes matters into his own hands.", poster:`${T}/iLBOSExz5G9aajRa9gBVctnmIFU.jpg`, duration:153, language:"English", featured:false },
  { title:"Knives Out", year:2019, genre:["Mystery","Comedy","Crime"], rating:7.9, score:97, director:"Rian Johnson", cast:["Daniel Craig","Chris Evans","Ana de Armas"], description:"A detective investigates the death of a patriarch of an eccentric, combative family.", poster:`${T}/pThyQovXQrws2hmsbpQB5T0bhQY.jpg`, duration:130, language:"English", featured:false },
  { title:"Memento", year:2000, genre:["Mystery","Thriller"], rating:8.4, score:80, director:"Christopher Nolan", cast:["Guy Pearce","Carrie-Anne Moss","Joe Pantoliano"], description:"A man with short-term memory loss attempts to track down his wife's murderer.", poster:`${T}/yuNs09hvpHVU1cBTCAk9zxsL2oW.jpg`, duration:113, language:"English", featured:false },
  { title:"The Prestige", year:2006, genre:["Mystery","Drama","Thriller"], rating:8.5, score:76, director:"Christopher Nolan", cast:["Christian Bale","Hugh Jackman","Scarlett Johansson"], description:"Two stage magicians engage in a competitive rivalry leading to obsession and fatal consequences.", poster:`${T}/5MXyQfz8xUP3dIFPTubhTsbFY6N.jpg`, duration:130, language:"English", featured:false },
  { title:"Chinatown", year:1974, genre:["Mystery","Crime","Drama"], rating:8.2, score:99, director:"Roman Polanski", cast:["Jack Nicholson","Faye Dunaway","John Huston"], description:"A private detective hired to expose an adulterer finds himself embroiled in a web of deceit.", poster:`${T}/9OECNEDgAONppzYeGHuTbH3AKZE.jpg`, duration:130, language:"English", featured:false },
  { title:"Nightcrawler", year:2014, genre:["Thriller","Crime","Drama"], rating:7.8, score:95, director:"Dan Gilroy", cast:["Jake Gyllenhaal","Rene Russo","Riz Ahmed"], description:"A driven man desperate for work muscles into the world of L.A. crime journalism.", poster:`${T}/j9xiCBSCkZgHtHmaxulGM7aXNwQ.jpg`, duration:117, language:"English", featured:false },

  // ACTION / ADVENTURE
  { title:"Mad Max: Fury Road", year:2015, genre:["Action","Adventure","Sci-Fi"], rating:8.1, score:97, director:"George Miller", cast:["Tom Hardy","Charlize Theron","Nicholas Hoult"], description:"In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search of her homeland.", poster:`${T}/kqjL17yufvn9OVLyXYpvtyrFfak.jpg`, duration:120, language:"English", featured:false },
  { title:"Avengers: Endgame", year:2019, genre:["Action","Sci-Fi","Adventure"], rating:8.4, score:94, director:"Anthony Russo", cast:["Robert Downey Jr.","Chris Evans","Mark Ruffalo"], description:"The Avengers assemble once more to reverse Thanos's actions and restore balance to the universe.", poster:`${T}/or06FN3Dka5tukK1e9sl16pB3iy.jpg`, duration:181, language:"English", featured:false },
  { title:"John Wick", year:2014, genre:["Action","Thriller"], rating:7.4, score:86, director:"Chad Stahelski", cast:["Keanu Reeves","Michael Nyqvist","Alfie Allen"], description:"An ex-hitman comes out of retirement to track down the gangsters that killed his dog.", poster:`${T}/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg`, duration:101, language:"English", featured:false },
  { title:"Die Hard", year:1988, genre:["Action","Thriller"], rating:8.2, score:94, director:"John McTiernan", cast:["Bruce Willis","Alan Rickman","Bonnie Bedelia"], description:"An NYPD officer tries to save his wife and others taken hostage by German terrorists.", poster:`${T}/yFihWxQcmqcaBR31QM6Y8gT6aYV.jpg`, duration:132, language:"English", featured:false },
  { title:"Top Gun: Maverick", year:2022, genre:["Action","Drama"], rating:8.3, score:96, director:"Joseph Kosinski", cast:["Tom Cruise","Miles Teller","Jennifer Connelly"], description:"After thirty years, Maverick is still pushing the envelope as a top naval aviator.", poster:`${T}/62HCnUTziyWcpDaBO2i1DX17ljH.jpg`, duration:130, language:"English", featured:true },
  { title:"Mission Impossible Fallout", year:2018, genre:["Action","Adventure","Thriller"], rating:7.7, score:97, director:"Christopher McQuarrie", cast:["Tom Cruise","Henry Cavill","Ving Rhames"], description:"Ethan Hunt and his IMF team race against time after a mission goes wrong.", poster:`${T}/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg`, duration:147, language:"English", featured:false },
  { title:"Gladiator", year:2000, genre:["Action","Adventure","Drama"], rating:8.5, score:76, director:"Ridley Scott", cast:["Russell Crowe","Joaquin Phoenix","Connie Nielsen"], description:"A Roman general is betrayed and his family murdered; he comes to Rome as a gladiator seeking revenge.", poster:`${T}/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg`, duration:155, language:"English", featured:false },
  { title:"The Terminator", year:1984, genre:["Action","Sci-Fi","Thriller"], rating:8.1, score:100, director:"James Cameron", cast:["Arnold Schwarzenegger","Linda Hamilton","Michael Biehn"], description:"A cyborg is sent from the future on a deadly mission to kill a woman who will give birth to humanity's leader.", poster:`${T}/qvktm0BHcnmDpul4Hz01GIazWPr.jpg`, duration:107, language:"English", featured:false },
  { title:"Spider-Man Into the Spider-Verse", year:2018, genre:["Animation","Action","Adventure"], rating:8.4, score:97, director:"Bob Persichetti", cast:["Shameik Moore","Jake Johnson","Hailee Steinfeld"], description:"Teen Miles Morales becomes Spider-Man of his reality, crossing paths with five spider-people counterparts.", poster:`${T}/iiZZdoQBEYBv6id8su7ImL0ek3F.jpg`, duration:117, language:"English", featured:true },
  { title:"The Dark Knight Rises", year:2012, genre:["Action","Crime","Drama"], rating:8.4, score:87, director:"Christopher Nolan", cast:["Christian Bale","Tom Hardy","Anne Hathaway"], description:"Eight years after Joker's reign of anarchy, Batman must return from his self-imposed exile to face a masked terrorist.", poster:`${T}/hr0L2aueqlP2BYQ17Q9lgyw4c9j.jpg`, duration:164, language:"English", featured:false },

  // HORROR
  { title:"Get Out", year:2017, genre:["Horror","Thriller","Mystery"], rating:7.7, score:98, director:"Jordan Peele", cast:["Daniel Kaluuya","Allison Williams","Bradley Whitford"], description:"A young African-American visits his white girlfriend's parents where his uneasiness grows.", poster:`${T}/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg`, duration:104, language:"English", featured:false },
  { title:"Hereditary", year:2018, genre:["Horror","Drama","Mystery"], rating:7.3, score:89, director:"Ari Aster", cast:["Toni Collette","Alex Wolff","Milly Shapiro"], description:"A grieving family is haunted by disturbing secrets after the death of their secretive grandmother.", poster:`${T}/rfid9H5p9N0UNWdPMBQNXxNrXgN.jpg`, duration:127, language:"English", featured:false },
  { title:"The Shining", year:1980, genre:["Horror","Drama"], rating:8.4, score:84, director:"Stanley Kubrick", cast:["Jack Nicholson","Shelley Duvall","Danny Lloyd"], description:"A family heads to an isolated hotel for the winter where a sinister presence influences the father.", poster:`${T}/nRj5511mZdTl4saWEPoj9QroTIu.jpg`, duration:146, language:"English", featured:false },
  { title:"A Quiet Place", year:2018, genre:["Horror","Drama","Sci-Fi"], rating:7.5, score:95, director:"John Krasinski", cast:["Emily Blunt","John Krasinski","Millicent Simmonds"], description:"A family struggles to survive in a world inhabited by blind monsters with an acute sense of hearing.", poster:`${T}/nAU74GmpUk7t5iklEp3bufnDyPt.jpg`, duration:90, language:"English", featured:false },
  { title:"It", year:2017, genre:["Horror","Drama"], rating:7.3, score:86, director:"Andy Muschietti", cast:["Jaeden Martell","Bill Skarsgard","Finn Wolfhard"], description:"In 1989, a group of bullied kids band together to destroy a shapeshifting monster.", poster:`${T}/9E2y5Q7WlCVNEhP5GiVTjga1vlp.jpg`, duration:135, language:"English", featured:false },
  { title:"The Conjuring", year:2013, genre:["Horror","Mystery","Thriller"], rating:7.5, score:86, director:"James Wan", cast:["Patrick Wilson","Vera Farmiga","Ron Livingston"], description:"Paranormal investigators Ed and Lorraine Warren help a family terrorized by a dark presence.", poster:`${T}/wVYREutTvI2tmxr6ujrHT704wGF.jpg`, duration:112, language:"English", featured:false },
  { title:"Midsommar", year:2019, genre:["Horror","Drama","Mystery"], rating:7.1, score:83, director:"Ari Aster", cast:["Florence Pugh","Jack Reynor","Wilhelm Blomgren"], description:"A couple travels to Sweden to visit a fabled midsummer festival that takes a sinister turn.", poster:`${T}/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg`, duration:148, language:"English", featured:false },
  { title:"Psycho", year:1960, genre:["Horror","Mystery","Thriller"], rating:8.5, score:97, director:"Alfred Hitchcock", cast:["Anthony Perkins","Vera Miles","Janet Leigh"], description:"A Phoenix secretary embezzles money and checks into a remote motel run by a disturbed young man.", poster:`${T}/yz4QVqPx3h851X1D1C1Q1t9Dp6A.jpg`, duration:109, language:"English", featured:false },
  { title:"Us", year:2019, genre:["Horror","Thriller"], rating:6.8, score:93, director:"Jordan Peele", cast:["Lupita Nyong'o","Winston Duke","Elisabeth Moss"], description:"A family's vacation takes a sinister turn when they discover murderous doppelgangers of themselves.", poster:`${T}/ux2maIthopoGMaLFTmh1FqbFKPS.jpg`, duration:116, language:"English", featured:false },
  { title:"Nope", year:2022, genre:["Horror","Sci-Fi","Mystery"], rating:7.0, score:83, director:"Jordan Peele", cast:["Daniel Kaluuya","Keke Palmer","Steven Yeun"], description:"Residents in a rural gulch witness an extraordinary and chilling discovery.", poster:`${T}/AcKVlWaNVVVFQwynSr988bwkoxB.jpg`, duration:130, language:"English", featured:false },
  { title:"The Witch", year:2015, genre:["Horror","Mystery","Drama"], rating:6.9, score:91, director:"Robert Eggers", cast:["Anya Taylor-Joy","Ralph Ineson","Kate Dickie"], description:"A family in 1630s New England is torn apart by the forces of witchcraft and dark possession.", poster:`${T}/eQnFMfV0bbQFJLe4bZFEOkUv57n.jpg`, duration:92, language:"English", featured:false },
  { title:"Barbarian", year:2022, genre:["Horror","Mystery","Thriller"], rating:7.1, score:92, director:"Zach Cregger", cast:["Georgina Campbell","Bill Skarsgard","Justin Long"], description:"A woman arrives at her rental only to find it has been double-booked with a menacing stranger.", poster:`${T}/58pjTXh7ViW5rFhJbfZJsqf8R9u.jpg`, duration:102, language:"English", featured:false },

  // ANIMATION
  { title:"Spirited Away", year:2001, genre:["Animation","Fantasy","Adventure"], rating:8.6, score:97, director:"Hayao Miyazaki", cast:["Daveigh Chase","Suzanne Pleshette","Miyu Irino"], description:"A young girl enters a world ruled by gods, witches, and spirits where humans are changed into beasts.", poster:`${T}/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg`, duration:125, language:"Japanese", featured:false },
  { title:"Coco", year:2017, genre:["Animation","Family","Fantasy"], rating:8.4, score:97, director:"Lee Unkrich", cast:["Anthony Gonzalez","Gael Garcia Bernal","Benjamin Bratt"], description:"A young boy embarks on an extraordinary journey to the Land of the Dead.", poster:`${T}/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg`, duration:105, language:"English", featured:false },
  { title:"Spider-Man Across the Spider-Verse", year:2023, genre:["Animation","Action","Adventure"], rating:8.6, score:95, director:"Joaquim Dos Santos", cast:["Shameik Moore","Hailee Steinfeld","Oscar Isaac"], description:"Miles Morales catapults across the multiverse and encounters a team of Spider-People.", poster:`${T}/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg`, duration:140, language:"English", featured:true },
  { title:"The Lion King", year:1994, genre:["Animation","Family","Drama"], rating:8.5, score:93, director:"Roger Allers", cast:["Matthew Broderick","Jeremy Irons","James Earl Jones"], description:"Lion cub and future king Simba searches for his identity after the murder of his father Mufasa.", poster:`${T}/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg`, duration:88, language:"English", featured:false },
  { title:"Soul", year:2020, genre:["Animation","Comedy","Drama"], rating:8.1, score:95, director:"Pete Docter", cast:["Jamie Foxx","Tina Fey","Graham Norton"], description:"A jazz musician falls into the cosmic You Seminar that determines human personality.", poster:`${T}/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg`, duration:100, language:"English", featured:false },
  { title:"Princess Mononoke", year:1997, genre:["Animation","Fantasy","Adventure"], rating:8.4, score:92, director:"Hayao Miyazaki", cast:["Yoji Matsuda","Yuriko Ishida","Yuko Tanaka"], description:"A prince becomes involved in a struggle between forest gods and the humans who consume their land.", poster:`${T}/uGy4DCmM33I7l86W7iCskNkvmLD.jpg`, duration:134, language:"Japanese", featured:false },
  { title:"WALL-E", year:2008, genre:["Animation","Family","Sci-Fi"], rating:8.4, score:95, director:"Andrew Stanton", cast:["Ben Burtt","Elissa Knight","Jeff Garlin"], description:"A small waste-collecting robot inadvertently embarks on a space journey that will determine the fate of mankind.", poster:`${T}/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg`, duration:98, language:"English", featured:false },
  { title:"Up", year:2009, genre:["Animation","Family","Adventure"], rating:8.3, score:98, director:"Pete Docter", cast:["Edward Asner","Jordan Nagai","John Ratzenberger"], description:"An elderly widower travels to South America in a house lifted by balloons with an unexpected young stowaway.", poster:`${T}/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg`, duration:96, language:"English", featured:false },
  { title:"Howl's Moving Castle", year:2004, genre:["Animation","Fantasy","Romance"], rating:8.2, score:87, director:"Hayao Miyazaki", cast:["Chieko Baisho","Takuya Kimura","Akihiro Miwa"], description:"A young woman cursed with an old body goes on a quest to break the spell and falls in love with a wizard.", poster:`${T}/TkTP5J2GfCHbTXcByVMk3q1ldP.jpg`, duration:119, language:"Japanese", featured:false },
  { title:"Kung Fu Panda", year:2008, genre:["Animation","Action","Comedy"], rating:7.6, score:88, director:"Mark Osborne", cast:["Jack Black","Angelina Jolie","Dustin Hoffman"], description:"A clumsy panda who works in a noodle shop dreams of becoming a kung fu master.", poster:`${T}/wWt1cznooSVTKGMcQkLjDaXP4oX.jpg`, duration:92, language:"English", featured:false },
  { title:"Toy Story", year:1995, genre:["Animation","Family","Comedy"], rating:8.3, score:100, director:"John Lasseter", cast:["Tom Hanks","Tim Allen","Don Rickles"], description:"A cowboy doll is threatened by the arrival of a new spaceman figure as the favourite toy of the owner.", poster:`${T}/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg`, duration:81, language:"English", featured:false },
  { title:"Finding Nemo", year:2003, genre:["Animation","Family","Adventure"], rating:8.2, score:99, director:"Andrew Stanton", cast:["Albert Brooks","Ellen DeGeneres","Alexander Gould"], description:"After his son is captured by a diver, an overprotective clownfish sets out on a journey to bring him home.", poster:`${T}/2zh2ZDBSo3hQHtZqAMUgOFBTWxK.jpg`, duration:100, language:"English", featured:false },

  // ROMANCE
  { title:"La La Land", year:2016, genre:["Romance","Drama","Musical"], rating:8.0, score:91, director:"Damien Chazelle", cast:["Ryan Gosling","Emma Stone","John Legend"], description:"A jazz musician and an aspiring actress fall in love while pursuing their dreams in Los Angeles.", poster:`${T}/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg`, duration:128, language:"English", featured:false },
  { title:"Amelie", year:2001, genre:["Romance","Comedy","Fantasy"], rating:8.3, score:89, director:"Jean-Pierre Jeunet", cast:["Audrey Tautou","Mathieu Kassovitz","Rufus"], description:"A shy Parisian waitress decides to change the lives of those around her while struggling with her own isolation.", poster:`${T}/f0uorE7K7ggAkPRFpKNwM8igCFj.jpg`, duration:122, language:"French", featured:false },
  { title:"Before Sunrise", year:1995, genre:["Romance","Drama"], rating:8.1, score:100, director:"Richard Linklater", cast:["Ethan Hawke","Julie Delpy"], description:"A young man and woman meet on a train in Europe and disembark in Vienna to spend one romantic evening together.", poster:`${T}/3OB1rp4lmLgkXKBKe8VxGCVl6Ly.jpg`, duration:101, language:"English", featured:false },
  { title:"Eternal Sunshine of the Spotless Mind", year:2004, genre:["Romance","Sci-Fi","Drama"], rating:8.3, score:92, director:"Michel Gondry", cast:["Jim Carrey","Kate Winslet","Tom Wilkinson"], description:"A couple undergo a medical procedure to have each other erased from their memories.", poster:`${T}/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg`, duration:108, language:"English", featured:false },
  { title:"Past Lives", year:2023, genre:["Romance","Drama"], rating:7.8, score:98, director:"Celine Song", cast:["Greta Lee","Teo Yoo","John Magaro"], description:"Two childhood sweethearts separated from South Korea are reunited in New York City two decades later.", poster:`${T}/k3waqVXSnptSPPAEtA0we9IKNH6.jpg`, duration:106, language:"English", featured:false },
  { title:"Portrait of a Lady on Fire", year:2019, genre:["Romance","Drama"], rating:8.1, score:98, director:"Celine Sciamma", cast:["Noemie Merlant","Adele Haenel","Luana Bajrami"], description:"In 18th-century France, a painter falls in love with the subject of the portrait she has been commissioned to paint.", poster:`${T}/3xGus3scQwuRLIqMUJJMtMfLF0Q.jpg`, duration:122, language:"French", featured:false },
  { title:"Call Me by Your Name", year:2017, genre:["Romance","Drama"], rating:7.9, score:95, director:"Luca Guadagnino", cast:["Timothee Chalamet","Armie Hammer","Michael Stuhlbarg"], description:"In 1980s Italy, romance blossoms between a seventeen-year-old student and an older man hired as his father's assistant.", poster:`${T}/n2P8VELOzJCIAzJvlqNpMPz6JOL.jpg`, duration:132, language:"English", featured:false },

  // COMEDY
  { title:"Everything Everywhere All at Once", year:2022, genre:["Sci-Fi","Comedy","Action"], rating:7.8, score:95, director:"Daniel Kwan", cast:["Michelle Yeoh","Stephanie Hsu","Ke Huy Quan"], description:"A middle-aged Chinese immigrant is swept up in an outrageous adventure across the multiverse.", poster:`${T}/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg`, duration:139, language:"English", featured:true },
  { title:"The Grand Budapest Hotel", year:2014, genre:["Comedy","Drama","Mystery"], rating:8.1, score:91, director:"Wes Anderson", cast:["Ralph Fiennes","Tony Revolori","Saoirse Ronan"], description:"A concierge and his lobby boy become embroiled in murder and a painting theft at a famous European hotel.", poster:`${T}/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg`, duration:99, language:"English", featured:false },
  { title:"Parasite", year:2019, genre:["Thriller","Drama","Comedy"], rating:8.5, score:99, director:"Bong Joon-ho", cast:["Song Kang-ho","Lee Sun-kyun","Cho Yeo-jeong"], description:"A poor family schemes to become employed by a wealthy family by posing as highly qualified individuals.", poster:`${T}/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg`, duration:132, language:"Korean", featured:true },
  { title:"The Big Lebowski", year:1998, genre:["Comedy","Crime"], rating:8.1, score:80, director:"Joel Coen", cast:["Jeff Bridges","John Goodman","Julianne Moore"], description:"The Dude is mistaken for a millionaire of the same name and becomes entangled in a kidnapping plot.", poster:`${T}/aFZqGzCmTB0BcBSAbLSO9AKr8ug.jpg`, duration:117, language:"English", featured:false },
  { title:"In Bruges", year:2008, genre:["Comedy","Crime","Drama"], rating:7.9, score:97, director:"Martin McDonagh", cast:["Colin Farrell","Brendan Gleeson","Ralph Fiennes"], description:"Guilt-ridden after a job gone wrong, hitman Ray and his partner await orders in the medieval city of Bruges.", poster:`${T}/4EBZ0WCGpWQOBMSAIlbKBFIAEeN.jpg`, duration:107, language:"English", featured:false },
  { title:"Superbad", year:2007, genre:["Comedy"], rating:7.6, score:88, director:"Greg Mottola", cast:["Jonah Hill","Michael Cera","Emma Stone"], description:"Two co-dependent high school seniors deal with separation anxiety when their plan to lose their virginity goes awry.", poster:`${T}/ek8e8txUyUwd2BNqj6lFEerJfms.jpg`, duration:113, language:"English", featured:false },
  { title:"The Favourite", year:2018, genre:["Comedy","Drama","History"], rating:7.5, score:94, director:"Yorgos Lanthimos", cast:["Olivia Colman","Emma Stone","Rachel Weisz"], description:"In early 18th century England, a frail Queen occupies the throne while two women scheme for her favour.", poster:`${T}/9COP4pnWUYnkXf81PxKhyBZw1ni.jpg`, duration:119, language:"English", featured:false },

  // WAR
  { title:"1917", year:2019, genre:["War","Drama","Action"], rating:8.3, score:89, director:"Sam Mendes", cast:["George MacKay","Dean-Charles Chapman","Mark Strong"], description:"Two British soldiers are sent on a dangerous mission to deliver a message that could save 1,600 lives.", poster:`${T}/iZf0KyrE25z1sage4SYFLCCrMi9.jpg`, duration:119, language:"English", featured:false },
  { title:"Saving Private Ryan", year:1998, genre:["War","Drama","Action"], rating:8.6, score:92, director:"Steven Spielberg", cast:["Tom Hanks","Matt Damon","Tom Sizemore"], description:"Following D-Day, U.S. soldiers search for a paratrooper whose brothers have been killed in combat.", poster:`${T}/uqx37cS8cpHg8U35f9U5IBlrCV3.jpg`, duration:169, language:"English", featured:false },
  { title:"Dunkirk", year:2017, genre:["War","Action","Drama"], rating:7.8, score:92, director:"Christopher Nolan", cast:["Fionn Whitehead","Tom Hardy","Mark Rylance"], description:"Allied soldiers surrounded by the German Army are evacuated during a fierce WWII battle.", poster:`${T}/ebSnODDg9lbsMIaWg2uAbjn7TO5.jpg`, duration:106, language:"English", featured:false },
  { title:"Apocalypse Now", year:1979, genre:["War","Drama"], rating:8.4, score:98, director:"Francis Ford Coppola", cast:["Martin Sheen","Marlon Brando","Robert Duvall"], description:"A special operations officer is sent into Cambodia to assassinate a renegade Special Forces Colonel.", poster:`${T}/gQB8Y5RCMkv2zwzFHbUJX3kAhvA.jpg`, duration:147, language:"English", featured:false },
  { title:"Full Metal Jacket", year:1987, genre:["War","Drama"], rating:8.3, score:96, director:"Stanley Kubrick", cast:["Matthew Modine","R. Lee Ermey","Vincent D'Onofrio"], description:"A pragmatic U.S. Marine observes the dehumanizing effects of the Vietnam War on his fellow recruits.", poster:`${T}/4ER6serkYLhFuSmGZklKNSRoHLe.jpg`, duration:116, language:"English", featured:false },
  { title:"Hacksaw Ridge", year:2016, genre:["War","Drama","Biography"], rating:8.1, score:84, director:"Mel Gibson", cast:["Andrew Garfield","Sam Worthington","Luke Bracey"], description:"The story of Desmond Doss, the conscientious objector who saved 75 men at the Battle of Okinawa without firing a shot.", poster:`${T}/xwBOtUlHXFGTqHuCqsUkfEWo9f1.jpg`, duration:139, language:"English", featured:false },

  // FANTASY / ADVENTURE
  { title:"The Lord of the Rings The Fellowship of the Ring", year:2001, genre:["Fantasy","Adventure","Drama"], rating:8.9, score:91, director:"Peter Jackson", cast:["Elijah Wood","Ian McKellen","Viggo Mortensen"], description:"A meek Hobbit and eight companions set out on a journey to destroy the powerful One Ring.", poster:`${T}/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg`, duration:178, language:"English", featured:true },
  { title:"The Lord of the Rings The Return of the King", year:2003, genre:["Fantasy","Adventure","Drama"], rating:9.0, score:93, director:"Peter Jackson", cast:["Elijah Wood","Viggo Mortensen","Ian McKellen"], description:"Gandalf and Aragorn lead the World of Men against Sauron's army while Frodo and Sam approach Mount Doom.", poster:`${T}/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg`, duration:201, language:"English", featured:false },
  { title:"Harry Potter and the Prisoner of Azkaban", year:2004, genre:["Fantasy","Adventure","Family"], rating:7.9, score:90, director:"Alfonso Cuaron", cast:["Daniel Radcliffe","Emma Watson","Rupert Grint"], description:"Harry Potter, Ron and Hermione return to Hogwarts and deal with mysterious new revelations.", poster:`${T}/aWxwnYoe8p2d2fcxOqtvAtJ72Rw.jpg`, duration:142, language:"English", featured:false },
  { title:"Pan's Labyrinth", year:2006, genre:["Fantasy","Drama","War"], rating:8.2, score:98, director:"Guillermo del Toro", cast:["Ivana Baquero","Sergi Lopez","Doug Jones"], description:"In Falangist Spain of 1944, a girl escapes into a labyrinthine world of wonder and terror.", poster:`${T}/htaAHnp66p8Um8SvZPMNnDYKmAO.jpg`, duration:118, language:"Spanish", featured:false },
  { title:"The Princess Bride", year:1987, genre:["Fantasy","Romance","Comedy"], rating:8.1, score:97, director:"Rob Reiner", cast:["Cary Elwes","Robin Wright","Mandy Patinkin"], description:"A farmboy turned pirate goes to rescue his true love in a story of adventure and romance.", poster:`${T}/gpTMqpNrDmMVJPELAkHygqKLiQV.jpg`, duration:98, language:"English", featured:false },
  { title:"The Wizard of Oz", year:1939, genre:["Fantasy","Adventure","Family"], rating:8.1, score:98, director:"Victor Fleming", cast:["Judy Garland","Frank Morgan","Ray Bolger"], description:"Dorothy is swept away to the magical land of Oz and embarks on a quest to find the Wizard.", poster:`${T}/glMeoccBM7LBSmNYLnTBIKmGEMQ.jpg`, duration:102, language:"English", featured:false },

  // BIOGRAPHY
  { title:"Bohemian Rhapsody", year:2018, genre:["Biography","Drama","Music"], rating:8.0, score:61, director:"Bryan Singer", cast:["Rami Malek","Lucy Boynton","Gwilym Lee"], description:"The story of the legendary British rock band Queen and lead singer Freddie Mercury.", poster:`${T}/lHu1wtNaczFPGFDTrjCSzeLPTKN.jpg`, duration:134, language:"English", featured:false },
  { title:"The Social Network", year:2010, genre:["Biography","Drama"], rating:7.8, score:96, director:"David Fincher", cast:["Jesse Eisenberg","Andrew Garfield","Justin Timberlake"], description:"As Mark Zuckerberg creates Facebook, he is sued by the twins who claim he stole their idea.", poster:`${T}/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg`, duration:120, language:"English", featured:false },
  { title:"Amadeus", year:1984, genre:["Biography","Drama","Music"], rating:8.4, score:96, director:"Milos Forman", cast:["F. Murray Abraham","Tom Hulce","Elizabeth Berridge"], description:"The story of Antonio Salieri and his obsessive jealousy of the genius of Mozart.", poster:`${T}/2mP48bKoVpWVmJOBFRRaNs2ORJH.jpg`, duration:160, language:"English", featured:false },
  { title:"I Tonya", year:2017, genre:["Biography","Drama","Sport"], rating:7.5, score:90, director:"Craig Gillespie", cast:["Margot Robbie","Sebastian Stan","Allison Janney"], description:"Based on the true story of U.S. figure skater Tonya Harding and the 1994 attack on her rival.", poster:`${T}/4qOBONNfHl3RmJQsS8NVMzpVZhb.jpg`, duration:119, language:"English", featured:false },
  { title:"The Imitation Game", year:2014, genre:["Biography","Drama","History"], rating:8.0, score:90, director:"Morten Tyldum", cast:["Benedict Cumberbatch","Keira Knightley","Matthew Goode"], description:"Based on the real life story of Alan Turing and how he cracked the Enigma code during WWII.", poster:`${T}/noUp0XOqIcmgefRnRZa1nhtRvWO.jpg`, duration:114, language:"English", featured:false },

  // FOREIGN LANGUAGE
  { title:"Oldboy", year:2003, genre:["Mystery","Action","Drama"], rating:8.1, score:80, director:"Park Chan-wook", cast:["Choi Min-sik","Yoo Ji-tae","Kang Hye-jung"], description:"After being imprisoned for 15 years, a man is released and put on a quest to find his captor.", poster:`${T}/pWDtjs568ZfOTMbURQBRC5iSpaY.jpg`, duration:120, language:"Korean", featured:false },
  { title:"City of God", year:2002, genre:["Crime","Drama"], rating:8.6, score:91, director:"Fernando Meirelles", cast:["Alexandre Rodrigues","Leandro Firmino","Phellipe Haagensen"], description:"In the slums of Rio, two boys grow up and choose opposite paths.", poster:`${T}/k7eYdWvhYQyRQoU2TB2A2Xu2grZ.jpg`, duration:130, language:"Portuguese", featured:false },
  { title:"Roma", year:2018, genre:["Drama"], rating:7.7, score:96, director:"Alfonso Cuaron", cast:["Yalitza Aparicio","Marina de Tavira"], description:"A year in the life of a middle-class family's domestic worker in 1970s Mexico City.", poster:`${T}/dtFOBMRTHBJy2E00N6k2a7Kf6gA.jpg`, duration:135, language:"Spanish", featured:false },
  { title:"Crouching Tiger Hidden Dragon", year:2000, genre:["Action","Fantasy","Romance"], rating:7.9, score:97, director:"Ang Lee", cast:["Yun-Fat Chow","Michelle Yeoh","Ziyi Zhang"], description:"Two warriors pursue a stolen sword and a fugitive in the world of martial arts.", poster:`${T}/a0RqKSuZH9vAG2YLW1EZwpacB1R.jpg`, duration:120, language:"Mandarin", featured:false },
  { title:"Life Is Beautiful", year:1997, genre:["Drama","Comedy","Romance"], rating:8.6, score:80, director:"Roberto Benigni", cast:["Roberto Benigni","Nicoletta Braschi","Giorgio Cantarini"], description:"A Jewish librarian uses his imagination to shield his young son from the harsh realities of the Holocaust.", poster:`${T}/74hLDKjD5aGYOotO6esUVaeISa2.jpg`, duration:116, language:"Italian", featured:false },
  { title:"The Lives of Others", year:2006, genre:["Drama","Thriller","History"], rating:8.4, score:97, director:"Florian Henckel von Donnersmarck", cast:["Ulrich Muhe","Martina Gedeck","Sebastian Koch"], description:"In 1984 East Berlin, a Stasi officer begins to question his assignment to spy on a playwright.", poster:`${T}/hSaR9ZVHBE8p2RO0hJ4KdSIStbV.jpg`, duration:137, language:"German", featured:false },
  { title:"Bicycle Thieves", year:1948, genre:["Drama"], rating:8.3, score:100, director:"Vittorio De Sica", cast:["Lamberto Maggiorani","Enzo Staiola","Lianella Carell"], description:"In post-war Rome, a man and his young son search desperately for his stolen bicycle.", poster:`${T}/rEHP8ylEkp6Gj0xtiLFPxvsBdlI.jpg`, duration:89, language:"Italian", featured:false },
  { title:"Seven Samurai", year:1954, genre:["Action","Drama","Adventure"], rating:8.6, score:100, director:"Akira Kurosawa", cast:["Toshiro Mifune","Takashi Shimura","Keiko Tsushima"], description:"A poor village under attack by bandits recruits seven unemployed samurai to defend them.", poster:`${T}/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg`, duration:207, language:"Japanese", featured:false },
  { title:"Rashomon", year:1950, genre:["Crime","Drama","Mystery"], rating:8.2, score:99, director:"Akira Kurosawa", cast:["Toshiro Mifune","Machiko Kyo","Masayuki Mori"], description:"The murder of a samurai is recounted by four witnesses, each telling the story differently.", poster:`${T}/zP3UrJ42s0XC5QubKDDiL48jrEN.jpg`, duration:88, language:"Japanese", featured:false },
  { title:"Y Tu Mama Tambien", year:2001, genre:["Drama","Romance"], rating:7.7, score:92, director:"Alfonso Cuaron", cast:["Maribel Verdu","Gael Garcia Bernal","Diego Luna"], description:"Two teenage boys and an older woman embark on a road trip and learn life-altering lessons.", poster:`${T}/7w5urEGsHSvHEJkJ0kfNP1GBNWH.jpg`, duration:106, language:"Spanish", featured:false },

  // RECENT 2023-2024
  { title:"Poor Things", year:2023, genre:["Comedy","Drama","Sci-Fi"], rating:8.0, score:91, director:"Yorgos Lanthimos", cast:["Emma Stone","Mark Ruffalo","Willem Dafoe"], description:"The incredible tale about the fantastical evolution of Bella Baxter, a young woman brought back to life.", poster:`${T}/kCGlIMHnOm8JPXIf6Xnd67cGBgN.jpg`, duration:141, language:"English", featured:false },
  { title:"The Holdovers", year:2023, genre:["Comedy","Drama"], rating:7.9, score:88, director:"Alexander Payne", cast:["Paul Giamatti","Dominic Sessa","Da'Vine Joy Randolph"], description:"A cantankerous teacher at a New England prep school is forced to remain on campus over the holidays with a reluctant student.", poster:`${T}/VHSzNBTwxV8vh7wylo7MXDeViO.jpg`, duration:133, language:"English", featured:false },
  { title:"Killers of the Flower Moon", year:2023, genre:["Crime","Drama","History"], rating:7.7, score:89, director:"Martin Scorsese", cast:["Leonardo DiCaprio","Robert De Niro","Lily Gladstone"], description:"Members of the Osage Nation in Oklahoma are murdered under mysterious circumstances in the 1920s.", poster:`${T}/dB6Sea7OrINSPHNEDHtIJqFjIjf.jpg`, duration:206, language:"English", featured:false },
  { title:"Saltburn", year:2023, genre:["Thriller","Drama","Mystery"], rating:7.0, score:71, director:"Emerald Fennell", cast:["Barry Keoghan","Jacob Elordi","Rosamund Pike"], description:"A student at Oxford becomes enamored with a charming aristocrat and is invited to his eccentric family estate.", poster:`${T}/qjhahNLSZ705B5JP92YMEYPocPz.jpg`, duration:127, language:"English", featured:false },
  { title:"Barbie", year:2023, genre:["Comedy","Fantasy","Adventure"], rating:6.9, score:88, director:"Greta Gerwig", cast:["Margot Robbie","Ryan Gosling","America Ferrera"], description:"Barbie and Ken embark on a journey of self-discovery after Barbie starts having thoughts of death.", poster:`${T}/iuFNMS8vlbGFVFqrFxGKPREL7KB.jpg`, duration:114, language:"English", featured:false },
  { title:"American Fiction", year:2023, genre:["Comedy","Drama"], rating:7.5, score:92, director:"Cord Jefferson", cast:["Jeffrey Wright","Tracee Ellis Ross","John Ortiz"], description:"A frustrated novelist uses a pen name to write a parody of Black literature that becomes a massive hit.", poster:`${T}/3f9XqO4bVdxFU9vxSEqNKwQMWcW.jpg`, duration:117, language:"English", featured:false },
  { title:"Priscilla", year:2023, genre:["Drama","Biography","Romance"], rating:6.7, score:80, director:"Sofia Coppola", cast:["Cailee Spaeny","Jacob Elordi","Ari Cohen"], description:"A look at the relationship between Elvis and Priscilla Presley told from her perspective.", poster:`${T}/rydaHnqJH4VTdHBM0bFXsEOaISB.jpg`, duration:113, language:"English", featured:false },
  { title:"The Zone of Interest", year:2023, genre:["Drama","History","War"], rating:7.9, score:93, director:"Jonathan Glazer", cast:["Christian Friedel","Sandra Huller"], description:"The commandant of Auschwitz and his wife try to build a dream life in a house next to the camp.", poster:`${T}/hUu9zyZmKuTuOKQgCwITRATUYKC.jpg`, duration:105, language:"German", featured:false },

  // DOCUMENTARY
  { title:"Free Solo", year:2018, genre:["Documentary","Adventure"], rating:8.2, score:99, director:"Elizabeth Chai Vasarhelyi", cast:["Alex Honnold","Tommy Caldwell"], description:"Alex Honnold becomes the first person to ever free solo climb El Capitan's 3,000-foot vertical rock face.", poster:`${T}/v1CEdnPjzKgXkSSK1HMuZGYqcEY.jpg`, duration:100, language:"English", featured:false },
  { title:"13th", year:2016, genre:["Documentary","History"], rating:8.2, score:97, director:"Ava DuVernay", cast:["Melina Abdullah","Michelle Alexander"], description:"An in-depth look at the prison system in the United States and the nation's history of racial inequality.", poster:`${T}/oVuswB0bCKanBeMYQFMjAeXTJXE.jpg`, duration:100, language:"English", featured:false },
  { title:"Amy", year:2015, genre:["Documentary","Music","Biography"], rating:7.8, score:95, director:"Asif Kapadia", cast:["Amy Winehouse","Mitch Winehouse","Mark Ronson"], description:"A look at the life of Amy Winehouse in her own words, featuring unseen archival footage.", poster:`${T}/3c6pzreTcmJrEfriCT5yqX7YQHI.jpg`, duration:128, language:"English", featured:false },

  // SPORT
  { title:"Moneyball", year:2011, genre:["Sport","Drama","Biography"], rating:7.6, score:94, director:"Bennett Miller", cast:["Brad Pitt","Jonah Hill","Philip Seymour Hoffman"], description:"Oakland A's general manager Billy Beane attempts to assemble a baseball team using computer-generated analysis.", poster:`${T}/3oAa8mJJ97CH9AeGEY6vjAxqcvZ.jpg`, duration:133, language:"English", featured:false },
  { title:"Rocky", year:1976, genre:["Drama","Sport"], rating:8.1, score:93, director:"John G. Avildsen", cast:["Sylvester Stallone","Talia Shire","Burt Young"], description:"A small-time boxer gets a once-in-a-lifetime chance to fight the heavyweight champion.", poster:`${T}/5zlsFQFwsOiPXAz8jGFVv41uf4T.jpg`, duration:120, language:"English", featured:false },
  { title:"Rush", year:2013, genre:["Sport","Drama","Biography"], rating:8.1, score:88, director:"Ron Howard", cast:["Chris Hemsworth","Daniel Bruhl","Olivia Wilde"], description:"The rivalry between Formula One racers James Hunt and Niki Lauda during the 1976 season.", poster:`${T}/4kBO14TkVE2U0sCDPM28bNJYdWf.jpg`, duration:123, language:"English", featured:false },
  { title:"Ford v Ferrari", year:2019, genre:["Sport","Drama","Biography"], rating:8.1, score:92, director:"James Mangold", cast:["Matt Damon","Christian Bale","Jon Bernthal"], description:"American car designer Carroll Shelby and fearless British driver Ken Miles battle corporate interference to build a race car for Le Mans.", poster:`${T}/6ApDtO7xaWAfnVQNqoO23RKNe23.jpg`, duration:152, language:"English", featured:false },
];

// Deduplicate by title + year
const seen = new Set();
const unique = movies.filter(m => {
  const key = `${m.title.toLowerCase().trim()}-${m.year}`;
  if (seen.has(key)) return false;
  seen.add(key);
  return true;
});

async function seed() {
  try {
    await Movie.deleteMany({});
    console.log("Cleared existing movies\n");
    const inserted = await Movie.insertMany(unique);
    console.log(`Seeded ${inserted.length} movies successfully!\n`);

    const byGenre = {};
    inserted.forEach(m => m.genre.forEach(g => { byGenre[g] = (byGenre[g] || 0) + 1; }));
    const byLang = {};
    inserted.forEach(m => { byLang[m.language] = (byLang[m.language] || 0) + 1; });

    console.log("Movies by genre:");
    Object.entries(byGenre).sort((a,b) => b[1]-a[1]).forEach(([g,c]) => {
      console.log(`  ${g.padEnd(22)} ${c}`);
    });
    console.log("\nMovies by language:");
    Object.entries(byLang).sort((a,b) => b[1]-a[1]).forEach(([l,c]) => console.log(`  ${l.padEnd(15)} ${c}`));
    console.log("\nTop 5 rated:");
    [...inserted].sort((a,b)=>b.rating-a.rating).slice(0,5).forEach(m => console.log(`  ${m.rating} - ${m.title} (${m.year})`));
  } catch (err) {
    console.error("Seed error:", err.message);
  } finally {
    await mongoose.disconnect();
    console.log("\nDisconnected from MongoDB");
  }
}

seed();
